### ISSUE TITLE
想請問問題

### ISSUE THREAD

**Issue by arguskao** [jschang19/plusone-linebot#3]
var current_hour = Utilities.formatDate(new Date(), "Asia/Taipei", "HH");
這裡的HH是幾個小時，但是是從何時開始計時？
機器人出現開始算嗎？

謝謝！

再度感謝您寫出這麼棒的教學
因為網頁上找不到地方留言
所以才到Github留言

**Comment by jschang19** [comment]
Hi 當有人傳 +1 時，程式會查看當下觸發的時間（ 小時數 ）所以嚴格來說它不算「從某時」開始計時，只是檢查收到 +1 訊息的當下時間，不知道這樣能否回答到您的疑問？
